We know that if we have a matic $A$, and multiply it by its inverse $A^{-1}$, we get the indenity matrix $I$.

Let's set $A^{-1} = B$ just to keep the notation simple.

We have
$$AB = I.$$

For a $3\times 3$ matrix,

$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\begin{pmatrix}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\
b_{31} & b_{32} & b_{33}
\end{pmatrix} = 
\begin{pmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{pmatrix}
$$

This becomes three individual  matrix equations.  One for each colum of the inverse matrix.

$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\begin{pmatrix}
b_{11}  \\
b_{21}  \\
b_{31} 
\end{pmatrix} = 
\begin{pmatrix}
1  \\
0  \\
0 
\end{pmatrix}
$$

$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\begin{pmatrix}
b_{12} \\
b_{22} \\
b_{32}
\end{pmatrix} = 
\begin{pmatrix}
0 \\
1 \\
0
\end{pmatrix}
$$

$$
\begin{pmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33}
\end{pmatrix}
\begin{pmatrix}
b_{13} \\
b_{23} \\
b_{33}
\end{pmatrix} = 
\begin{pmatrix}
0 \\
0 \\
1
\end{pmatrix}
$$

In [16]:
import numpy as np
from scipy.linalg import lu, lu_solve, lu_factor

In [17]:
np.random.seed(1)

#  Let's invert this matrix via LU decomposition
A = np.random.normal( size = (3, 3))
print(A)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]


In [18]:
#  Calculate and print p0, L, and U.  
p0, L, U = lu(A, permute_l=False)
print(p0); print()
print(L); print()
print(U); print()

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

[[ 1.          0.          0.        ]
 [-0.61494807  1.          0.        ]
 [ 0.93095737  0.24388009  1.        ]]

[[ 1.74481176 -0.7612069   0.3190391 ]
 [ 0.          0.39730492 -2.10534622]
 [ 0.          0.         -0.31173153]]



In [19]:
#  lu_solve takes the matrices L and U in a combiined form where the ones on the diagonal of the L matrix are removed.
#  We then add this to the U matrix to get them into a more compressed form.
for i in range(L.shape[0]):
    L[i,i] = 0
    
LU = L + U

#  The P matrix is represented with a vector.  Here, the 2 means row two is now in the first row, etc.
p = np.array([2,1,0])

#  Enter the vevtors of knowns and permute them.
I1 = np.array([1,0,0]); I1 = p0 @ I1
I2 = np.array([0,1,0]); I2 = p0 @ I2
I3 = np.array([0,0,1]); I3 = p0 @ I3

#  Solve for the columns of our inverse matrix
b1 = lu_solve( (LU, p), I1)
b2 = lu_solve( (LU, p), I2)
b3 = lu_solve( (LU, p), I3)

# Make these explicitly column vectors
b1.shape = (3,1)
b2.shape = (3,1)
b3.shape = (3,1)

#  Join them togther into a single matrix
A_inv = np.hstack( (b1,b2,b3) )
print(A_inv)

[[ -6.82949293   2.76364776   8.63059432]
 [-16.99882312   6.66263299  19.92235287]
 [ -3.20788853   0.78234013   3.46750601]]


In [20]:
#  Is our answer the same as Numpy's built-in inv function?
A_num = np.linalg.inv(A)
np.allclose(A_num, A_inv)

True